added select component
nftfy/nftfy-sweep-flip-v1 pull request #28
Opened 2023-01-11 21:01 UTC by paulobarcelosbr

2023-01-12 18:20 UTC, luanpontolio commented on src/components/ExpiresSelectTime.tsx
> +      options={[
Maybe we can create a CONSTANT for this, what do you think?

2023-01-12 18:58 UTC, arthurmr96 requested changes

2023-01-12 18:58 UTC, arthurmr96 commented on src/components/ExpiresSelectTime.tsx
> +      defaultValue='lucy'
Why `lucy`?

2023-01-13 13:08 UTC, paulobarcelosbr commented on src/components/ExpiresSelectTime.tsx
> +      options={[
since this is a simple component I don't think it's necessary.

2023-01-13 13:24 UTC, arthurmr96 approved these changes

2023-01-13 14:37 UTC, merged