Added portifolio components
nftfy/nftfy-sweep-flip-v1 pull request #31
Opened 2023-01-16 12:59 UTC by paulobarcelosbr

2023-01-16 14:21 UTC, arthurmr96 requested changes

2023-01-16 14:21 UTC, arthurmr96 commented on pages/portifolio/[walletAddress]/index.tsx
> +interface PortifolioPageProps {
```suggestion
interface PortiolioPageProps {
```

2023-01-16 14:21 UTC, arthurmr96 commented on pages/portifolio/[walletAddress]/index.tsx
> +export default function PortifolioPage({ walletAddress, fallback }: PortifolioPageProps) {
```suggestion
export default function PortfolioPage({ walletAddress, fallback }: PortfolioPageProps) {
```

2023-01-16 14:21 UTC, arthurmr96 commented on pages/sweep-flip/index.tsx
>      <Content chainId={chainId} />
Isn't it good to remove also this `chainId` here?

2023-01-16 14:21 UTC, arthurmr96 commented on pages/portifolio/[walletAddress]/index.tsx
> +        walletAddress,
Add here revalidation since this page will be generated. It's important to list the new NFTs that the user can sweep

2023-01-16 14:21 UTC, arthurmr96 commented on src/components/portifolio/Portifolio.tsx
> +    includeTopBid: true
Why include this param?

2023-01-16 14:21 UTC, arthurmr96 commented on src/components/portifolio/Portifolio.tsx
> +function Portifolio({ walletAddress, fallback }: PortifolioProps) {
```suggestion
function Portfolio({ walletAddress, fallback }: PortifolioProps) {
```

2023-01-16 14:21 UTC, arthurmr96 commented on src/components/portifolio/Portifolio.tsx
> +export interface PortifolioProps {
```suggestion
export interface PortfolioProps {
```

2023-01-16 14:21 UTC, arthurmr96 commented on src/components/portifolio/Portifolio.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Why did you ignored this rule?

2023-01-16 14:21 UTC, arthurmr96 commented on src/components/portifolio/Portifolio.tsx
> +    tokens: paths['/users/{user}/tokens/v5']['get']['responses']['200']['schema']
Can't this interface be called directly from the definitions? And why are you calling it as `fallback?`

2023-01-16 15:02 UTC, paulobarcelosbr commented on pages/sweep-flip/index.tsx
>      <Content chainId={chainId} />
yes the layout component did not use the chainid

2023-01-16 15:03 UTC, paulobarcelosbr commented on src/components/portifolio/Portifolio.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
I need this snippet to render only once

2023-01-16 15:08 UTC, luanpontolio commented on src/components/portifolio/UserAvatar.tsx
> +import Jazzicon, { jsNumberForAddress } from 'react-jazzicon'
There is a component similar to this `components/Avatar.tsx`. You can use them instead of creating another one.

2023-01-16 17:48 UTC, paulobarcelosbr commented on src/components/portifolio/Portifolio.tsx
> +    includeTopBid: true
and an ordering parameter, uses the aggregator as a base.

2023-01-16 17:51 UTC, paulobarcelosbr commented on src/components/portifolio/UserAvatar.tsx
> +import Jazzicon, { jsNumberForAddress } from 'react-jazzicon'
the component sits, apparently the css is not getting properly.

2023-01-16 19:16 UTC, paulobarcelosbr commented on src/components/portifolio/UserAvatar.tsx
> +import Jazzicon, { jsNumberForAddress } from 'react-jazzicon'
I recreated the component removing tailwind

2023-01-16 19:52 UTC, arthurmr96 requested changes

2023-01-16 19:52 UTC, arthurmr96 commented on src/components/portifolio/Portfolio.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Why did you disabled this rule?

2023-01-16 19:59 UTC, arthurmr96 commented on pages/sweep-flip/index.tsx
>      <Content chainId={chainId} />
I mean on `Component`

2023-01-16 20:02 UTC, arthurmr96 requested changes

2023-01-16 20:02 UTC, arthurmr96 commented on src/components/portifolio/Portfolio.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Instead of disabling the rule, use a boolean state to control the execution

2023-01-16 20:02 UTC, arthurmr96 commented on styles/theme.light.less
> +// @table-header-bg: @primary-color-2;
Why did you commented this line?

2023-01-17 14:27 UTC, arthurmr96 approved these changes

2023-01-17 14:28 UTC, merged