added collection on route
nftfy/nftfy-sweep-flip-v1 pull request #47
Opened 2023-01-25 20:39 UTC by paulobarcelosbr

2023-01-26 13:12 UTC, arthurmr96 requested changes

2023-01-26 13:12 UTC, arthurmr96 commented on src/components/SweepFlipForm.tsx
> +      setCollectionData(routeCollection[0])
Why you're getting the first position of an array if the `routeCollection` is a string?

2023-01-26 13:14 UTC, paulobarcelosbr commented on src/components/SweepFlipForm.tsx
> +      setCollectionData(routeCollection[0])
is  a Array of collection

2023-01-26 13:25 UTC, arthurmr96 commented on src/components/SweepFlipForm.tsx
> +      setCollectionData(routeCollection[0])
Then you should better type the state to be an array, what do you think? So it gets clear that you're dealing with an array

2023-01-26 13:28 UTC, arthurmr96 requested changes

2023-01-26 13:28 UTC, arthurmr96 commented on src/components/SweepFlipForm.tsx
> +  const [routeCollectionSelected, setRouteCollectionSelected] = useState('')
```suggestion
  const [routeCollectionSelected, setRouteCollectionSelected] = useState<string[]>([])
```

2023-01-27 12:59 UTC, arthurmr96 approved these changes

2023-01-27 12:59 UTC, merged